### PR TITLE
Adds path for MacOS X

### PR DESCRIPTION
**Pull request by mulderp**
This works for the Blink.ino on MacOS X for me ::)

### CODE REVIEW

**Comment by sej7278** [comment]
have you looked at https://github.com/sudar/Arduino-Makefile ?

**Comment by hexagon5un** [comment]
Thanks tons Patrick!  That's awesome.

(And sej7278: no.  I'm on my way!)

**Comment by mulderp** [comment]
Cool. The Arduino-Makefile project is nice, but it does "too much", at least for simple sketches like a blinking LED :)

**Comment by sej7278** [comment]
@mulderp sure, but the point is you have Arduino.mk installed in /usr/share/arduino and just a tiny Makefile alongside your sketch, so my Blink makefile consists entirely of:

```
BOARD_TAG = leonardo
MONITOR_PORT = /dev/ttyACM0
include /usr/share/arduino/Arduino.mk
```

**Comment by mulderp** [comment]
Interesting to have it as include file, did not try that approach. For sure, the Arduino-Makefile project works. Just needed a simpler solution to bundle some C/.ino project with some easy steps to build it. 

The Arduino-Makefile project is quite large, includes things to monitor the serial port (which I would do with a script in Node.js), and a script to restart the board with Python (which I would like to do with Node.js too).

For Ruby users, it seems that someone else tried this approach to parse a Ctags file: https://github.com/michaelbaisch/uDino-Preprocessor/issues/1

By the way, in Node.js this solution looks nice to build a sketch: https://github.com/AdamMagaluk/leo - which someone pointed me in https://github.com/Pinoccio/js-stk500/issues/7 - but a simple Makefile is often easier to understand.

**Pull request merged**
